### ISSUE TITLE
Pipelines started crashing in last few hours

### ISSUE THREAD

**Issue by Durisvk** [Azure/webapps-deploy#10]
The jobs started to crash with `Error: Cannot find module 'azure-actions-webclient/webClient'` which is imported in https://github.com/microsoft/pipelines-appservice-lib/blob/master/packages/appservice-rest/src/Kudu/KuduServiceClient.ts#L3

_I believe the issue is caused by one of the last few commits made in this repository:_

https://github.com/Azure/webapps-deploy/commit/bbd69d2cbae29328417a9b4d8469f2dd12e7e169

https://github.com/Azure/webapps-deploy/commit/007249dab7e1dde37723f36c91eeb663bd9dbc90

_this one looks the most suspicious:_
https://github.com/Azure/webapps-deploy/commit/54291e6252e122e21264f9ec6ab7df4cbe8f80e8

**Configuration:**

```yaml
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v1
        with:
          app-name: my-app-name-on-azure
          publish-profile: ${{ secrets.STAGING_AZURE_WEBAPP_PUBLISH_PROFILE }}
```

**Logs:**

```
2019-12-19T11:30:34.4883155Z ##[group]Run azure/webapps-deploy@v1
2019-12-19T11:30:34.4883365Z with:
2019-12-19T11:30:34.4883506Z   app-name: staging-coinflip-aaa-hostedsite
2019-12-19T11:30:34.4884718Z   publish-profile: ***
2019-12-19T11:30:34.4884923Z   package: .
2019-12-19T11:30:34.4885057Z   slot-name: production
2019-12-19T11:30:34.4885191Z env:
2019-12-19T11:30:34.4885326Z   CI: true
2019-12-19T11:30:34.4885516Z   SLACK_WEBHOOK: ***
2019-12-19T11:30:34.4885810Z   SLACK_CHANNEL: ci-cd
2019-12-19T11:30:34.4885926Z   SLACK_PRE_MESSAGE: *Deployed Feature:* 
2019-12-19T11:30:34.4886033Z   REPO_SLUG: oakslab/coinflip-AAA-hosted-site
2019-12-19T11:30:34.4886136Z   COMMIT_MESSAGE: 
2019-12-19T11:30:34.4886234Z   COMMIT_ID: 
2019-12-19T11:30:34.4886331Z ##[endgroup]
2019-12-19T11:30:34.6426081Z internal/modules/cjs/loader.js:800
2019-12-19T11:30:34.6426497Z     throw err;
2019-12-19T11:30:34.6426646Z     ^
2019-12-19T11:30:34.6426727Z 
2019-12-19T11:30:34.6427637Z Error: Cannot find module 'azure-actions-webclient/webClient'
2019-12-19T11:30:34.6427819Z Require stack:
2019-12-19T11:30:34.6428710Z - /home/runner/work/_actions/azure/webapps-deploy/v1/node_modules/azure-actions-appservice-rest/Kudu/KuduServiceClient.js
2019-12-19T11:30:34.6429531Z - /home/runner/work/_actions/azure/webapps-deploy/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js
2019-12-19T11:30:34.6430125Z - /home/runner/work/_actions/azure/webapps-deploy/v1/node_modules/azure-actions-appservice-rest/Utilities/AzureAppServiceUtility.js
2019-12-19T11:30:34.6430643Z - /home/runner/work/_actions/azure/webapps-deploy/v1/lib/deploymentProvider/WebAppDeploymentProvider.js
2019-12-19T11:30:34.6431219Z - /home/runner/work/_actions/azure/webapps-deploy/v1/lib/main.js
2019-12-19T11:30:34.6431446Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
2019-12-19T11:30:34.6431817Z     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
2019-12-19T11:30:34.6432392Z     at Module.require (internal/modules/cjs/loader.js:852:19)
2019-12-19T11:30:34.6432625Z     at require (internal/modules/cjs/helpers.js:74:18)
2019-12-19T11:30:34.6433288Z     at Object.<anonymous> (/home/runner/work/_actions/azure/webapps-deploy/v1/node_modules/azure-actions-appservice-rest/Kudu/KuduServiceClient.js:13:21)
2019-12-19T11:30:34.6433615Z     at Module._compile (internal/modules/cjs/loader.js:959:30)
2019-12-19T11:30:34.6433853Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2019-12-19T11:30:34.6434083Z     at Module.load (internal/modules/cjs/loader.js:815:32)
2019-12-19T11:30:34.6434305Z     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
2019-12-19T11:30:34.6434589Z     at Module.require (internal/modules/cjs/loader.js:852:19) {
2019-12-19T11:30:34.6434978Z   code: 'MODULE_NOT_FOUND',
2019-12-19T11:30:34.6435149Z   requireStack: [
2019-12-19T11:30:34.6435855Z     '/home/runner/work/_actions/azure/webapps-deploy/v1/node_modules/azure-actions-appservice-rest/Kudu/KuduServiceClient.js',
2019-12-19T11:30:34.6436343Z     '/home/runner/work/_actions/azure/webapps-deploy/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js',
2019-12-19T11:30:34.6436861Z     '/home/runner/work/_actions/azure/webapps-deploy/v1/node_modules/azure-actions-appservice-rest/Utilities/AzureAppServiceUtility.js',
2019-12-19T11:30:34.6437596Z     '/home/runner/work/_actions/azure/webapps-deploy/v1/lib/deploymentProvider/WebAppDeploymentProvider.js',
2019-12-19T11:30:34.6437969Z     '/home/runner/work/_actions/azure/webapps-deploy/v1/lib/main.js'
2019-12-19T11:30:34.6438115Z   ]
2019-12-19T11:30:34.6438250Z }
2019-12-19T11:30:34.6478547Z ##[error]Node run failed with exit code 1
```

@SumiranAgg can you please take a look at it? it's kind of urgent.

**Comment by christiandw** [comment]
@SumiranAgg Having the exact same issue - currently unable to deploy via Actions

![Screenshot from 2019-12-19 14-04-38](https://user-images.githubusercontent.com/54848451/71175788-a6e21900-2268-11ea-9e11-cd0bc047b250.png)

**Comment by SumiranAgg** [comment]
Could be a regression. Will rollback.

**Comment by riverbit** [comment]
I can confirm that the issue still persists.

**Comment by SumiranAgg** [comment]
Are you pointing to azure/webapps-deploy@v1 ? Or is it releases/v1

**Comment by riverbit** [comment]
It's `Azure/webapps-deploy@v1`

**Comment by riverbit** [comment]
I have just restarted the test and it does work now. Thanks @SumiranAgg for your quick help!

**Comment by SumiranAgg** [comment]
Glad to know its working!
