### ISSUE TITLE
v3 faield to reboot webapp due to 401, but v2 is OK

### ISSUE THREAD

**Issue by copdips** [Azure/webapps-deploy#379]
Hello,

I just swtiched the action azure/webapps-deploy from `v2` to `v3`, and I encountered a reboot error as post-deployment step due to 401, switching back to `v2` got deploy successfully.

My workflow is similar to:

```yaml
- uses: actions/checkout@main

- uses: azure/login@v1
  with:
    creds: ${{ secrets.AZURE_CREDENTIALS }}
          
- name: Run Azure webapp deploy action using Azure Credentials
  uses: azure/webapps-deploy@v3
  with: 
    app-name: myapp
    package: site
```

Please find hereunder the deploy log:

```console
...(some logs are omitted)
Build completed succesfully.

Running post deployment command(s)...

Requesting site restart

Requesting site restart. Attempt #1

Requesting site restart. Attempt #2

Requesting site restart. Attempt #3

Requesting site restart. Attempt #4

Requesting site restart. Attempt #5

Failed to request a restart. Number of attempts: 5. Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
 at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
 at Kudu.Core.Helpers.PostDeploymentHelper.PostAsync(String path, String requestId, String content) in /tmp/KuduLite/Kudu.Core/Helpers/PostDeploymentHelper.cs:line 670
 at Kudu.Core.Helpers.PostDeploymentHelper.<>c__DisplayClass38_0.<<RestartMainSiteAsync>b__0>d.MoveNext() in /tmp/KuduLite/Kudu.Core/Helpers/PostDeploymentHelper.cs:line 349
--- End of stack trace from previous location ---
 at Kudu.Core.Infrastructure.OperationManager.<>c__DisplayClass4_0.<<AttemptAsync>b__0>d.MoveNext() in /tmp/KuduLite/Kudu.Core/Infrastructure/OperationManager.cs:line 58
--- End of stack trace from previous location ---
 at Kudu.Core.Infrastructure.OperationManager.AttemptAsync[TVal](Func`1 action, Int32 retries, Int32 delayBeforeRetry) in /tmp/KuduLite/Kudu.Core/Infrastructure/OperationManager.cs:line 82
 at Kudu.Core.Helpers.PostDeploymentHelper.RestartMainSiteAsync(String requestId, TraceListener tracer) in /tmp/KuduLite/Kudu.Core/Helpers/PostDeploymentHelper.cs:line 343
3:03:46 PM
Deployment Failed. deployer = OneDeploy deploymentPath = OneDeploy
```

**Comment by copdips** [comment]
it's an active question

**Comment by dannysongg** [comment]
Hi @copdips 
Can you provide the name of the webapp you are trying to deploy to?

**Comment by copdips** [comment]
hi @dannysongg 
Thank you for your reply, is there anyway that I can send you private message, as it's a company webapp.

**Comment by dannysongg** [comment]
@copdips feel free to send me an email at dannysong@microsoft.com

**Comment by copdips** [comment]
hi @dannysongg,

while preparing the logs and re-testing the v3, it's working now, so I'll close this issue, and thank you very much for your followup !

```json
[
    {
        "log_time": "2024-01-29T08:45:49.5702607Z",
        "id": "1a64ef6e-66ee-465e-b528-002eaf853dc4",
        "message": "Updating submodules.",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:50.6665362Z",
        "id": "14ad63ad-1b5b-410d-9372-78c558fca9eb",
        "message": "Preparing deployment for commit id '06319561-b'.",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:50.803761Z",
        "id": "117b1675-42d0-4379-9dd1-82153fd69ede",
        "message": "PreDeployment: context.CleanOutputPath False",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:50.8549055Z",
        "id": "c7fe9282-e6d4-4983-8b26-fc52fb971292",
        "message": "PreDeployment: context.OutputPath /home/site/wwwroot",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:50.9570043Z",
        "id": "9c320fc5-e49a-488b-8bd6-f5b88a040b36",
        "message": "Running build. Project type: OneDeploy",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:51.0089821Z",
        "id": "8c83412a-d0d5-4c99-bf74-1cdc2578f17f",
        "message": "Copying the manifest",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:51.1131272Z",
        "id": "e3442bf4-3195-4d45-9a22-0465b5a4e2be",
        "message": "Clean deploying to /home/site/wwwroot",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:51.1689337Z",
        "id": "db39563e-2ece-4a1f-a562-e4b22aaae332",
        "message": "Generating deployment script.",
        "type": 0,
        "details_url": "https://test.scm.azurewebsites.net/api/deployments/06319561-b364-4747-818a-e778ac36b3e3/log/db39563e-2ece-4a1f-a562-e4b22aaae332"
    },
    {
        "log_time": "2024-01-29T08:45:51.2450703Z",
        "id": "5d80a207-1ef6-42a6-b3aa-33a487514b96",
        "message": "Running deployment command...",
        "type": 0,
        "details_url": "https://test.scm.azurewebsites.net/api/deployments/06319561-b364-4747-818a-e778ac36b3e3/log/5d80a207-1ef6-42a6-b3aa-33a487514b96"
    },
    {
        "log_time": "2024-01-29T08:45:55.3867814Z",
        "id": "089dddc5-141e-43dc-b053-bb2c02b93c8a",
        "message": "Build completed succesfully.",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:55.4358687Z",
        "id": "f023f425-ebce-49ec-99ca-70acc05b9dbd",
        "message": "Running post deployment command(s)...",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:55.5068292Z",
        "id": "62258f65-951f-4a6a-853c-7c147f647e38",
        "message": "Requesting site restart",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:55.5591885Z",
        "id": "6fbc7889-9509-4f3b-85b7-1cca841180c7",
        "message": "Requesting site restart. Attempt #1",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:55.7380656Z",
        "id": "209fd8c4-19f2-4790-bb41-dbc001ade155",
        "message": "Successfully requested a restart. Attempt #1",
        "type": 0,
        "details_url": null
    },
    {
        "log_time": "2024-01-29T08:45:55.7994719Z",
        "id": "9ba1ee30-0e5a-41a4-9597-4ba4ae4100dc",
        "message": "Deployment successful. deployer = OneDeploy deploymentPath = OneDeploy",
        "type": 0,
        "details_url": null
    }
]
```
