### ISSUE TITLE
Successful deployment reported despite old version still running

### ISSUE THREAD

**Issue by aiimi-cclifton** [Azure/webapps-deploy#384]
This has been causing me to scratch my head for some time, and while I assume more a core Azure issue, I'm unsure where to report it. 

We are maintaining a .NET 6.0 web app, which has and can be successfully published from Visual Studio

Attempt to deploy the project from CI/CD appear successful, they show in the deployment centre and when you FTP onto the box, the deployment and logs appear under `/site/deployments`, however `wwwroot` remains untouched, with last modified remaining as the last date deployed through visual studio

There is not trace of error in the github action, however here are the full deployment logs (with some chars replaced with x's):
```
2023-12-08T16:24:57.8032242Z,Updating submodules.,xxxxxxx-524d-40d9-8447-4f1b8b0b55d,0
2023-12-08T16:24:57.8955282Z,Preparing deployment for commit id 'xxxxxx'.,xxxxxx-6c7c-4897-be85-,0
2023-12-08T16:24:58.3336180Z,Running build. Project type: OneDeploy,xxxxxxx-12fa-40b3-a277-,0
2023-12-08T16:24:58.3954941Z,Copying the manifest,xxxxxx-b52e-455b-b691-,0
2023-12-08T16:24:58.4579820Z,Clean deploying to C:\home\site\wwwroot,xxxxxxx-4622-44bc-899c-,0
2023-12-08T16:24:58.4899385Z,Generating deployment script.,xxxxxxxx-39f2-479d-bb40-,0
	2023-12-08T16:24:58.5531074Z,Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"'.,,0
	2023-12-08T16:25:00.1327231Z,C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153,,1
	2023-12-08T16:25:00.1509723Z,                ...StatusLogger.DEFAULT_STATUS&comma;,,1
	2023-12-08T16:25:00.1945599Z,                ^^^,,1
	2023-12-08T16:25:00.2279123Z,,,1
	2023-12-08T16:25:00.2413032Z,SyntaxError: Unexpected token ...,,1
	2023-12-08T16:25:00.2725500Z,    at createScript (vm.js:56:10),,1
	2023-12-08T16:25:00.2881783Z,    at Object.runInThisContext (vm.js:97:10),,1
	2023-12-08T16:25:00.3040370Z,    at Module._compile (module.js:542:28),,1
	2023-12-08T16:25:00.3194280Z,    at Object.Module._extensions..js (module.js:579:10),,1
	2023-12-08T16:25:00.3672026Z,    at Module.load (module.js:487:32),,1
	2023-12-08T16:25:00.3975421Z,    at tryModuleLoad (module.js:446:12),,1
	2023-12-08T16:25:00.4600428Z,    at Function.Module._load (module.js:438:3),,1
	2023-12-08T16:25:00.4787040Z,    at Module.require (module.js:497:17),,1
	2023-12-08T16:25:00.5072257Z,    at module.js:669:12,,1
	2023-12-08T16:25:00.5381777Z,    at Array.forEach (native),,1
	2023-12-08T16:25:00.5850253Z,C:\PROGRA~2\SITEEX~1\NODEAP~1\296456~1.8\nodejs\build\src\Loader.js:153\r\n                ...StatusLogger.DEFAULT_STATUS&comma;\r\n                ^^^\r\n\r\nSyntaxError: Unexpected token ...\r\n    at createScript (vm.js:56:10)\r\n    at Object.runInThisContext (vm.js:97:10)\r\n    at Module._compile (module.js:542:28)\r\n    at Object.Module._extensions..js (module.js:579:10)\r\n    at Module.load (module.js:487:32)\r\n    at tryModuleLoad (module.js:446:12)\r\n    at Function.Module._load (module.js:438:3)\r\n    at Module.require (module.js:497:17)\r\n    at module.js:669:12\r\n    at Array.forEach (native)\r\nC:\Program Files (x86)\SiteExtensions\Kudu\100.51108.6494\bin\Scripts\starter.cmd "C:\Program Files (x86)\SiteExtensions\Kudu\100.51108.6494\bin\node_modules\.bin\kuduscript.cmd" -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted",,2
2023-12-08T16:25:00.6475279Z,Build completed succesfully.,xxxxxxx-cfb4-4728-8ba4-786754602c7f,0
2023-12-08T16:25:00.6943941Z,Running post deployment command(s)...,xxxxxxx-2b5f-4ae0-bc05-14e31a5d1231,0
2023-12-08T16:25:00.7881477Z,Requesting site restart,xxxxxxx-f2e1-475b-89e6-4c671a573b17,0
2023-12-08T16:25:00.8667504Z,Requesting site restart. Attempt #xxxxxxx-281a-4bc1-988c-0413894d6337,0
2023-12-08T16:25:01.4130930Z,Successfully requested a restart. Attempt #1,xxxxxx-10ba-4d1e-b0ec-d6983e174e91,0
2023-12-08T16:25:01.4912170Z,Deployment successful.,xxxxxx-7af7-4699-8c54-0239002cd5dc,0
```

Presumably the stack trace is related, but as you can see it reports success when it has in fact failed

**Comment by aiimi-cclifton** [comment]
The problem was resolved, so I can confirm it was related to the stack call (unsurprisingly) updating a node via the `WEBSITE_NODE_DEFAULT_VERSION` application setting in azure _and_ remembering to save it allowed me to deploy and see changes. 

The issue remains open though, as:
   1. The stack trace is caught and the deployment assumed successful
   2. The stack trace was not bubbled up to the Github Action; I had to FTP onto the server and view the log on there

**Comment by terrynguyen255** [comment]
Still facing this
