### ISSUE TITLE
util_1.promisify is not a function

### ISSUE THREAD

**Issue by RashmiBK5** [Azure/webapps-deploy#422]
I am trying to deploy .net core Web Api (.net 6) to Azure web app but I am getting an error 
"**_C:\PROGRA~2\SITEEX~1\NODEAP~1\210~1.4\nodejs\node_modules\applicationinsights\out\Library\FileSystemHelper.js:43
exports.statAsync = util_1.promisify(fs.stat);_**"

the same workflow was working fine till last working day, but all of a sudden it is throwing exception 

**_Log from last working day:_**
Generate deployment script was success full with script:

Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"').

But now getting an error related to Node.js.

### Yaml File:

    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
    
     - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.FredApiAppService_0F0E }}
        package: '.'

### Error:

Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"'.
C:\PROGRA~2\SITEEX~1\NODEAP~1\210~1.4\nodejs\node_modules\applicationinsights\out\Library\FileSystemHelper.js:43
exports.statAsync = util_1.promisify(fs.stat);
                           ^

TypeError: util_1.promisify is not a function
    at Object.<anonymous> (C:\PROGRA~2\SITEEX~1\NODEAP~1\210~1.4\nodejs\node_modules\applicationinsights\out\Library\FileSystemHelper.js:43:28)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\PROGRA~2\SITEEX~1\NODEAP~1\210~1.4\nodejs\node_modules\applicationinsights\out\Library\InternalAzureLogger.js:48:24)
    at Module._compile (module.js:577:32)
C:\PROGRA~2\SITEEX~1\NODEAP~1\210~1.4\nodejs\node_modules\applicationinsights\out\Library\FileSystemHelper.js:43\r\nexports.statAsync = util_1.promisify(fs.stat);\r\n                           ^\r\n\r\nTypeError: util_1.promisify is not a function\r\n    at Object.<anonymous> (C:\PROGRA~2\SITEEX~1\NODEAP~1\210~1.4\nodejs\node_modules\applicationinsights\out\Library\FileSystemHelper.js:43:28)\r\n    at Module._compile (module.js:577:32)\r\n    at Object.Module._extensions..js (module.js:586:10)\r\n    at Module.load (module.js:494:32)\r\n    at tryModuleLoad (module.js:453:12)\r\n    at Function.Module._load (module.js:445:3)\r\n    at Module.require (module.js:504:17)\r\n    at require (internal/module.js:20:19)\r\n    at Object.<anonymous> (C:\PROGRA~2\SITEEX~1\NODEAP~1\210~1.4\nodejs\node_modules\applicationinsights\out\Library\InternalAzureLogger.js:48:24)\r\n    at Module._compile (module.js:577:32)\r\nC:\Program Files (x86)\SiteExtensions\Kudu\102.10502.001\bin\Scripts\starter.cmd "C:\Program Files (x86)\SiteExtensions\Kudu\102.10502.001\bin\node_modules\.bin\kuduscript.cmd" -y --no-dot-deployment -r "C:\local\Temp\zipdeploy\extracted" -o "C:\home\site\deployments\tools" --basic --sitePath "C:\local\Temp\zipdeploy\extracted"

**Comment by AndyEdmonds** [comment]
I'm getting exactly the same error trying to deploy several  webapps.

**Comment by RashmiBK5** [comment]
Hi @AndyEdmonds 
I added WEBSITE_NODE_DEFAULT_VERSION =14.17.0 in Web app environment setting and it started working.

**Comment by AndyEdmonds** [comment]
Hi Rashmi, Thanks, will try it.

**Comment by casepulvec** [comment]
Hi @RashmiBK5 
Thank you so much for your reply. I had the same issue for several days when trying to deploy a bot from Bot Framework Composer to App Services App and Azure Bot Services. Setting the environment variable WEBSITE_NODE_DEFAULT_VERSION as 14.17.0, allow me to finally deploy the app. 

For future reference, if someone else has the same issue when deploying an app from Bot Framework Composer, the following are the errors I was able to solve by following Rashmi's recommendations.
Error from Bot Framework Composer
![thumbnail_image](https://github.com/Azure/webapps-deploy/assets/140927456/6d63d486-dc4f-4962-8784-c8266fa37445)

Error log in App Services
![image](https://github.com/Azure/webapps-deploy/assets/140927456/efa1c7a5-25c4-4a71-9de8-87cba465d52c)
![image](https://github.com/Azure/webapps-deploy/assets/140927456/9c8ec719-15c0-4c9b-aac4-26ed940ba334)

**Comment by baodv1001** [comment]
> 14.17.0

I applied this fix and it worked. thanks!

**Comment by Gary-Mason-Arc-Regulatory** [comment]
I know this is late to the party so apologies but I thought it would be useful to give an explanation of how i fixed it through Azure without setting any environment variables. I discovered that, in my case, i had set the application insights incorrectly for my .net application. I messed around for some time and then realized i had turned on the deployment slots, which has it's own environment variables. So i went through each env variable for each slot and removed all mentions to application insights, including WEBSITE_NODE_DEFAULT_VERSION. I then re-enabled application insights, for the correct environment, on each slot and this fixed it for me.
