### ISSUE TITLE
Error: Cannot find module 'azure-actions-webclient/webClient

### ISSUE THREAD

**Issue by jacob-j** [Azure/webapps-deploy#59]
Hello!
Not sure if this is a place to report this, as there seems to be no activity in the issues tab here.
But I'll try, and if no reply, try somewhere else.

We have been getting this error lately:
It is causing our builds to fire an error, but it's working anyways.

```
Error: Cannot find module 'azure-actions-webclient/webClient'
Require stack:
- /home/runner/work/_actions/azure/webapps-container-deploy/v1/node_modules/azure-actions-appservice-rest/Kudu/KuduServiceClient.js
- /home/runner/work/_actions/azure/webapps-container-deploy/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js
- /home/runner/work/_actions/azure/webapps-container-deploy/v1/node_modules/azure-actions-appservice-rest/Utilities/AzureAppServiceUtility.js
- /home/runner/work/_actions/azure/webapps-container-deploy/v1/lib/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/azure/webapps-container-deploy/v1/node_modules/azure-actions-appservice-rest/Kudu/KuduServiceClient.js:13:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/azure/webapps-container-deploy/v1/node_modules/azure-actions-appservice-rest/Kudu/KuduServiceClient.js',
    '/home/runner/work/_actions/azure/webapps-container-deploy/v1/node_modules/azure-actions-appservice-rest/Kudu/azure-app-kudu-service.js',
    '/home/runner/work/_actions/azure/webapps-container-deploy/v1/node_modules/azure-actions-appservice-rest/Utilities/AzureAppServiceUtility.js',
    '/home/runner/work/_actions/azure/webapps-container-deploy/v1/lib/main.js'
  ]
*******
```

**Comment by aksm-ms** [comment]
@jacob-j Are you still facing the issue?

**Comment by aksm-ms** [comment]
Closing the issue - not enough to debug. Please feel free to reopen in case of any queries.
